# Generated by Django 5.2.10 on 2026-05-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("company", models.CharField(blank=True, max_length=160)),
                (
                    "budget",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("under-10k", "Under $10k"),
                            ("10-25k", "$10k – $25k"),
                            ("25-75k", "$25k – $75k"),
                            ("75k-plus", "$75k+"),
                            ("unsure", "Not sure yet"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "source_site",
                    models.CharField(
                        choices=[
                            ("pulse", "Pulse"),
                            ("atelier", "Atelier"),
                            ("orbit", "Orbit"),
                            ("signal", "Signal"),
                            ("quiet", "Quiet"),
                            ("landing", "Landing"),
                        ],
                        default="landing",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("client", models.CharField(max_length=120)),
                ("category", models.CharField(max_length=80)),
                ("year", models.PositiveIntegerField()),
                ("summary", models.CharField(max_length=280)),
                ("body", models.TextField(blank=True)),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                (
                    "cover_color",
                    models.CharField(
                        default="#111111",
                        help_text="Fallback background when image missing.",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags.", max_length=240
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "metrics",
                    models.TextField(
                        blank=True,
                        help_text="One metric per line, format: 'Reach | 12M impressions'.",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-year", "title"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                (
                    "summary",
                    models.CharField(
                        help_text="One-line elevator pitch.", max_length=240
                    ),
                ),
                ("body", models.TextField(help_text="Plain text or simple HTML.")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Optional emoji or short label used by sites that want a glyph.",
                        max_length=40,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="services/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "deliverables",
                    models.TextField(
                        blank=True, help_text="One per line — used as a bullet list."
                    ),
                ),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField()),
                ("author", models.CharField(max_length=120)),
                ("role", models.CharField(max_length=120)),
                ("company", models.CharField(blank=True, max_length=120)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
